version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: dumb-init node /.output/server/index.mjs
